#!/bin/bash

# DrawBoxes, something I saw in Grasshopper and decided to also do because fuck you that's why
# In Grasshopper, they used letters, here I use numbers
# blue and black, both have `b` in it, see the issue?
# So instead, it works like this:
# 0 -> black
# 1 -> red
# 2 -> green
# 3 -> yellow
# 4 -> blue
# 5 -> magenta
# 6 -> cyan
# 7 -> white


# CONSTANTS
red="\033[0;31m"
yellow="\033[0;33m"
green="\033[0;32m"
blue="\033[0;34m"
magenta="\033[0;35m"
cyan="\033[0;36m"
black="\033[0;30m"
white="\033[0;97m"
reset="\033[0m"

hopper=" "
block="▇▇"

# REEEEEEEEEEEEEEEEEEEEEEEE
text="$@"
chars=$( printf "$text\n" | grep -o . | sed 's/ /~~/g')
tput civis
#echo ${chars[@]}
for char in ${chars[@]}; do
    case $char in 
    0) printf ${black}${block} ;;
    1) printf ${red}${block} ;;
    2) printf ${green}${block} ;;
    3) printf ${yellow}${block} ;;
    4) printf ${blue}${block} ;;
    5) printf ${magenta}${block} ;;
    6) printf ${cyan}${block} ;;
    7) printf ${white}${block} ;;
    "~~") printf " \n" ;;
    esac
    sleep 0.4
done
printf " \n"
tput cnorm
