#!/bin/sh
case $1 in
  *.rar) rar x $1 ${1%.rar}/ ;;
  *.tar.bz2) mkdir -p ${1%.tar.bz2} && tar xjf $1 -C ${1%.tar.bz2}/ ;;
  *.tar.gz) mkdir -p ${1%.tar.gz} && tar xzf $1 -C ${1%.tar.gz}/ ;;
  *.tar.xz) mkdir -p ${1%.tar.xz} && tar xf  $1 -C ${1%.tar.xz}/ ;;
  *.tar) mkdir -p ${1%.tar} && tar xf  $1 -C ${1%.tar}/ ;;
  *.tbz2) mkdir -p ${1%.tbz2} && tar xjf $1 -C ${1%.tbz2}/ ;;
  *.tgz) mkdir -p ${1%.tgz} && tar xzf $1 -C ${1%.tgz}/ ;;
  *.zip) unzip $1 -d ${1%.zip}/ ;;
  *.7z) 7za e $1 -o${1%.7z}/ ;;
  *.*) printf "'$1' cannot be extracted.\n" ;;
  *) printf "Usage: ext compressed_file.xyz\n";;
esac
