#!/usr/bin/bash

#colors
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
magenta="\033[1;35m"
cyan="\033[1;36m"
white="\033[1;37m"
end="\033[1;0m"
colors=($red $green $yellow $blue $magenta $cyan $white)
seed=${#colors[@]}

text="$@"

chars=$( printf "$text\n" | grep -o . | sed 's/ /~~/g')
for char in ${chars[@]}; do
  color=$(($RANDOM%${seed}))
  printf "${colors[$color]}" 
  printf "$char" | sed 's/~~/ /g'
done
printf " \n"
