#!/usr/bin/bash

welcome() {
printf "%s" "\

██    ██  ██████  ██      ██    ██ ███    ███ ███████ 
██    ██ ██    ██ ██      ██    ██ ████  ████ ██      
██    ██ ██    ██ ██      ██    ██ ██ ████ ██ █████   
 ██  ██  ██    ██ ██      ██    ██ ██  ██  ██ ██      
  ████    ██████  ███████  ██████  ██      ██ ███████ 

version 0.2: Kuzutetsu

Dependencies:
    - pamixer -> Pulseaudio controller
    - dunst -> a nice lil notifier

A pamixer wrapper script that uses dunst to send notifications
  Options:

  up -> Increases the volume

  down -> Decreases the volume

  toggle -> Mutes or Unmutes the volume
"
exit 1
}

# Variables
ID=500
APPNAME="volume_boi"
TOP_DECOR="      "
MUTE_MSG="U  D E D"
COLOR_A="#ebb9b9"   # RED
COLOR_B="#ebe3b9"   # YELLOW
COLOR_C="#caf6bb"   # GREEN
COLOR_D="#cddbf9"   # BLUE
COLOR_E="#2c2e3e"   # GREY


# Make sure you have the dependencies on 
dependencies=(bash dunst pamixer)

for dependency in "${dependencies[@]}"; do
    type -p "$dependency" &>/dev/null || {
        echo "error: Could not find '${dependency}', is it installed?" >&2
        exit 1
    }
done

# If someone wants to know how to use this
if [[ "$1" == "" ]] ; then
    welcome
fi


# Functions

# Get the volume thingy
function get_volume {
    local yeet=$(pamixer --get-volume-human)
    if [[ "$yeet" != "mute" ]] ; then
        yeet="${yeet%\%*}"
    fi
    echo $yeet
}

# Bar thingy (s t a r s)
function bar_thingy {
    # This is for 5 hearts btw
    #     
    full=""
    half=""
    empty=""

    volume=$(get_volume)

    total_half_hearts=$(( $(echo ${volume} / 10 | cut -f1 -d ".") ))

    half_hearts=$(( ${total_half_hearts} % 2 ))
    full_hearts=$(( ( ${total_half_hearts} - $(( ${total_half_hearts} % 2 )) ) / 2))
    empty_hearts=$(( 5 - ( ${full_hearts} + half_hearts ) ))

    local bar=$(echo $(echo $(seq -s " " $((${full_hearts}+1)) )$(seq -s " " $((${half_hearts}+1)) )$(seq -s " " $(($empty_hearts + 1)) ) ) | sed 's/[0-9]//g') 
    echo $bar
}

# Sends the notification
function dunsty_boi {
    volume=$(get_volume)

    # The other stuff
    if [[ "$volume" == "0"  ]] ; then
        icon_name="~/.config/dunst/icons/skull.svg"
    elif [[ "$volume" -lt "30"  ]] ; then
        icon_name="~/.config/dunst/icons/wand.svg"
    elif [[ "$volume" -lt "60" ]] ; then
        icon_name="~/.config/dunst/icons/wand_bling.svg"
    elif [[ "$volume" -lt "90" ]] ; then
        icon_name="~/.config/dunst/icons/spell_book.svg"
    else
        icon_name="~/.config/dunst/icons/wizard_hat.svg"
    fi
    # Send notification thing
    dunstify  -i $icon_name -r $ID -a $APPNAME -h string:fgcolor:"${COLOR_E}" "${TOP_DECOR}" "<span foreground='$COLOR_A' font_desc='Cartograph CF Italic 19'><b>Vo</b></span><span foreground='$COLOR_B' font_desc='Cartograph CF Italic 19'><b>lu</b></span><span foreground='$COLOR_C' font_desc='Cartograph CF Italic 19'><b>me</b></span>\n<span foreground='$COLOR_D' font_desc='Source Code Pro 23'><b>$(bar_thingy)</b></span>"
}


# Main thing
if [[ $# -gt 0 ]] ; then
    case "$1" in
        help)
            welcome
            ;;
        up)
            volume=$(get_volume)
            if [[ $volume != "muted" ]] ; then
                pamixer -i 10
                dunsty_boi
            fi
            ;;
        down)
            volume=$(get_volume)
            if [[ $volume != "muted" ]] ; then
                pamixer -d 10
                dunsty_boi
            fi
            ;;
        toggle)
            pamixer -t
            volume=$(get_volume)
            echo $volume
            if [[ "$volume" == "muted" ]] ; then
                icon_name="~/.config/dunst/icons/skull.svg"
                dunstify  -i $icon_name -r $ID -a $APPNAME -h string:fgcolor:"${COLOR_E}" "${TOP_DECOR}" "<span foreground='$COLOR_A' font_desc='Cartograph CF Italic 19'><b>Vo</b></span><span foreground='$COLOR_B' font_desc='Cartograph CF Italic 19'><b>lu</b></span><span foreground='$COLOR_C' font_desc='Cartograph CF Italic 19'><b>me</b></span>\n<span foreground='$COLOR_D' font_desc='Source Code Pro 23'><b>$MUTE_MSG</b></span>"
            else
                dunsty_boi
            fi
            ;;
        *)
            welcome
            ;;
    esac
fi

