#!/bin/sh

printf "${cr}"
#colors
cr="\033[1;31m"
cg="\033[1;32m"
cb="\033[1;34m"
#default config variables
height=720
width=1280
bg="#181818"
colors="#181818 #d8d8d8 #181818 #d8d8d8"
shape="circle"
file="wall.png"

#check for convert
if ! type convert >/dev/null; then
  printf "${cr}Error: Could not find 'convert', Make sure you have ImageMagick installed.\n" && exit 1;
fi

#better debugging
count=0
log() {
  count=$(($count + 1))
  printf "$count"
}

#help function
help() { printf "${cg}cw: create wallpaper (WIP)
  Usage: cw ${cb}[config_file] [output_file]${cg}(one included in test directory)
${cr}Report issues at: https://github.com/manas140/sh/\n" && exit; }

#generate random value between 2 numbers
random() {
  a=$(( $1 + $(date +%s%N) % $2 ))
  while [ $a -gt $2 ]; do
    a=$(( $1 + $(date +%s%N) % $2 ))
  done
  printf "$a\n"
}

#main
main() {
  #create a shape with random position and size for each color
  for color in $colors; do
    case $shape in 
      rectangle|circle)
        xs=$(random 0 $width)
        ys=$(random 0 $height)
        xe=$(random 0 $width)
        ye=$(random 0 $height);;
      *) printf "${cr}Error: Shape Not Supported\n"; exit 1;;
    esac
    #save it in a variable 'draw' which will be used later as a argument
    draw="$draw -fill \"$color\" -draw \"$shape $xs $ys $xe $ye\"";
  done
  #convert the variable 'draw' into a working command
  draw="convert -size \"$width\"x\"$height\" xc:$bg $draw -flatten $file"
  #run the 'draw' variable
  eval $draw
  printf "${cg}Wall Generated\n"
}

#arguments
case $1 in 
  "") printf "${cr}Error: No File Provided, Using Defaults\n";;
  *) #if file exist source it else show help
    if [ -f $1 ]; then
      . $(pwd)/$1
    else
      help
    fi;;
esac

#output_file 
case $2 in
  *.*) file=$2;;
esac

main
