#!/bin/sh

cr="\033[0;0m\033[1;31m"
cg="\033[0;0m\033[1;32m"
cb="\033[0;0m\033[1;34m"
help() { printf "${cg}run: run a script
Usage: run ${cb}[py|c|cpp|lua|sh] script${cb}
${cr}Report issues at: https://github.com/manas140/sh/\n"; }

if ! [ -f $2 ]; then
  printf "${cr}Error: No Such File '$file'\n" && exit 1;
fi

file=$2

case $1 in
  py) shift; shift
    printf "${cg}run: python $file $@\n\n"
    python $file $@;;
  c) shift; shift
    printf "${cg}run: gcc $file -o out && ./out $@\n\n"
    gcc $file -o out && ./out $@;;
  cpp) shift; shift
    printf "${cg}run: gcc $file -o out && ./out $@\n\n"
    gcc $file -o out && ./out $@;;
  lua) shift; shift
    printf "${cg}run: lua $file $@\n\n"
    lua $file $@;;
  sh) shift; shift
    printf "${cg}run: chmod +x $file && ./$file $@\n\n"
    chmod +x $file && ./$file $@;;
  *) help;;
esac
