#!/bin/sh

cr="\033[1;31m"
cg="\033[1;32m"
cb="\033[1;34m"

help() { printf "${cg}sing: print colored text
Example: sing ${cb}hello${cg}
Extra Juice: block ${cb}\"hello world\"${cg} >> file${cg}
${cr}Report issues at: https://github.com/manas140/sh/\n" && exit; }

case $1 in 
  "") printf "${cr}Error: No Value Provided\n" && exit 1;;
  *h|*help) help;;
esac

chars=$(printf "$@" | grep -o . | sed 's/ /~~/g')
for char in $chars; do 
  c=$(( $(date +%s%N) % 4 + 1))
  printf "\033[1;3%sm$char" "$c" | sed 's/~~/ /g'
done
printf "\n"
