#!/bin/sh

cr="\033[0;0m\033[1;31m"
cg="\033[0;0m\033[1;32m"
cb="\033[0;0m\033[1;34m"

trash=$HOME/.trash
if ! [ -d $trash ]; then
  mkdir $trash;
fi

help() { printf "${cg}trash: a trash utility
Usage: trash ${cb}[l|d|r|h] file${cg}
    ${cb}l:${cg} list
    ${cb}d:${cg} delete
    ${cb}r:${cg} recover
    ${cb}h:${cg} help
Example: trash ${cb}d file file1 file2${cg}
${cr}Report issues at: https://github.com/manas140/sh/\n" && exit; }

printf "${cr}"
case $1 in 
  l) ls --color="yes" -a $trash;;
  r) shift 
    for file in $@; do 
      mv $trash/$file $(pwd) && printf "${cg}[*] $file Recovered\n${cr}"
    done;;
  d) shift
    for file in $@; do
      mv $file $trash && printf "${cg}[*] $file Moved to Trash\n${cr}"
    done;;
  *) help;;
esac
